#ifndef MICROMOUSE_INCLUDE_MODEL_MOVESTATUS_H_
#define MICROMOUSE_INCLUDE_MODEL_MOVESTATUS_H_

enum MoveStatus {
  SUCCESS,
  GOAL_REACHED,
  START_REACHED,
  FAILURE,
};

#endif //MICROMOUSE_INCLUDE_MODEL_MOVESTATUS_H_
